name: Package Application with Pyinstaller

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: jp-vidya-ocr-linux
          path: src/dist/linux
